import dotenv from "dotenv";
dotenv.config();

export const {
  PORT,
  DB_URI,
  JWT_SECRET,
  JWT_REFRESH_SECRET,
  JWT_CONFIRM_EMAIL_SECRET,
  NODE_ENV,
  SUB_CATEGORY_DEFAULT,
  CATEGORY_DEFAULT,
  EMAIL_USERNAME,
  EMAIL_PASSWORD,
  RESET_PASSWORD_SECRET,
  FRONTEND_URL,
  BASE_URL,
} = process.env;
