const messages = {
  AUTH: {
    EMAIL_EXISTS: "Email đã được sử dụng",
    INVALID_EMAIL: "Email không hợp lệ",
    INVALID_PASSWORD: "Mật khẩu không đúng",
    USER_NOT_FOUND: "Người dùng không tồn tại",
    EMAIL_NOT_CONFIRMED: "Vui lòng xác nhận email trước khi đăng nhập",
    LOGIN_SUCCESS: "Đăng nhập thành công",
    REGISTER_SUCCESS:
      "Đăng ký thành công. Vui lòng kiểm tra email để xác nhận.",
    EMAIL_CONFIRMED: "Email đã được xác nhận",
    EMAIL_ALREADY_CONFIRMED: "Email đã được xác nhận trước đó",
    CONFIRM_TOKEN_MISSING: "Thiếu token xác nhận",
    CONFIRM_TOKEN_INVALID: "Token xác nhận không hợp lệ hoặc đã hết hạn",
    ROLE_NOT_FOUND: "Vai trò không tồn tại",
    UNAUTHORIZED: "Chưa xác thực",
    FORBIDDEN: "Bạn không có quyền truy cập",
    OTP_SENT: "Mã OTP đã được gửi đến email",
    INVALID_OTP: "OTP không chính xác",
    OTP_EXPIRED: "OTP đã hết hạn",
    PASSWORD_UPDATED: "Mật khẩu đã được cập nhật",
    INVALID_REFRESH_TOKEN: "Refresh token không hợp lệ hoặc đã bị thu hồi",
    MISSING_INFORMATION: "Vui lòng nhập đầy đủ thông tin",
    MISSING_REFRESH_TOKEN: "Thiếu refresh token",
  },
  CATEGORY: {
    CREATE_FAILED: "Tạo danh mục thất bại",
    NOT_FOUND: "Không tìm thấy danh mục",
    UPDATE_FORBIDDEN: "Không được phép sửa danh mục 'Không phân loại'",
    DELETE_FORBIDDEN: "Không được phép xóa danh mục 'Không phân loại'",
    SOFT_DELETE_SUCCESS:
      "Xóa mềm thành công, sản phẩm được chuyển sang danh mục 'Không phân loại'",
    RESTORE_SUCCESS:
      "Khôi phục danh mục thành công, sản phẩm được trả về danh mục cũ",
    HARD_DELETE_SUCCESS: "Xóa cứng thành công",
  },
  PRODUCT: {
    CREATE_SUCCESS: "Thêm sản phẩm thành công",
    CREATE_FAILED: "Tạo sản phẩm thất bại",
    NOT_FOUND: "Không tìm thấy sản phẩm",
    UPDATE_SUCCESS: "Cập nhật sản phẩm thành công",
    UPDATE_FAILED: "Cập nhật sản phẩm thất bại",
    HARD_DELETE_SUCCESS: "Xoá sản phẩm thành công",
    SOFT_DELETE_SUCCESS: "Đã xoá mềm sản phẩm",
    GET_DETAIL_SUCCESS: "Lấy chi tiết sản phẩm thành công",
    RESTORE_SUCCESS: "Khôi phục sản phẩm thành công",
    DELETE_FAILED: "Xoá sản phẩm thất bại",
    DETAIL_SUCCESS: "Chi tiết sản phẩm",
  },
  PRODUCT_VARIANT: {
    CREATE_SUCCESS: "Thêm biến thể thành công",
    CREATE_FAILED: "Tạo biến thể thất bại",
    NOT_FOUND: "Không tìm thấy biến thể",
    NOT_FOUND_ID: "Không tìm thấy ID sản phẩm",
    UPDATE_SUCCESS: "Cập nhật biến thể thành công",
    UPDATE_FAILED: "Cập nhật biến thể thất bại",
    HARD_DELETE_SUCCESS: "Xoá biến thể thành công",
    DELETE_FAILED: "Xoá biến thể thất bại",
    DETAIL_SUCCESS: "Chi tiết biến thể",
  },
  BRAND: {
    CREATE_SUCCESS: "Thêm thương hiệu thành công",
    CREATE_FAILED: "Tạo thương hiệu thất bại",
    NOT_FOUND: "Không tìm thấy thương hiệu",
    UPDATE_SUCCESS: "Cập nhật thương hiệu thành công",
    UPDATE_FAILED: "Cập nhật thương hiệu thất bại",
    HARD_DELETE_SUCCESS: "Xoá thương hiệu thành công",
    DELETE_FAILED: "Xoá thương hiệu thất bại",
    SOFT_DELETE_SUCCESS: "Đã xoá mềm thương hiệu",
    REGISTER_SUCCESS: "Khôi phục thương hiệu thành công",
    DETAIL_SUCCESS: "Chi tiết thương hiệu",
  },
  ORDER: {
    NOT_FOUND: "Không tìm thấy đơn hàng",
    UPDATE_SUCCESS: "Cập nhật đơn hàng thành công",
    UPDATE_FAILED: "Cập nhật đơn hàng thất bại",
    DETAIL_SUCCESS: "Chi tiết đơn hàng",
  },
  USER: {
    CREATE_SUCCESS: "Thêm tài khoản thành công",
    CREATE_FAILED: "Tạo tài khoản thất bại",
    NOT_FOUND: "Không tìm thấy tài khoản",
    UPDATE_SUCCESS: "Cập nhật tài khoản thành công",
    UPDATE_FAILED: "Cập nhật tài khoản thất bại",
    HARD_DELETE_SUCCESS: "Xoá tài khoản thành công",
    DELETE_FAILED: "Xoá tài khoản thất bại",
    SOFT_DELETE_SUCCESS: "Đã xoá mềm tài khoản",
    REGISTER_SUCCESS: "Khôi phục tài khoản thành công",
    DETAIL_SUCCESS: "Chi tiết tài khoản",
    NO_CHANGE_EMAIL: "Không được phép thay đổi email",
    EMAIL_EXISTS: "Email đã tồn tại"
  },
  PAYMENT: {
    NOT_FOUND: "Không tìm thấy thanh toán",
    UPDATE_SUCCESS: "Cập nhật thanh toán thành công",
    UPDATE_FAILED: "Cập nhật thanh toán thất bại",
    DETAIL_SUCCESS: "Chi tiết thanh toán",
    ORDER_ID_INVALID: "order id không hợp lệ",
    ID_INVALID: "id không hợp lệ",
    PAYMETN_STATUS_INVALID: "Trạng thái thanh toán không hợp lệ"
  },
  DISCOUNT: {
    CREATE_SUCCESS: "Thêm mã giảm giá thành công",
    CREATE_FAILED: "Tạo mã giảm giá thất bại",
    NOT_FOUND: "Không tìm thấy mã giảm giá",
    UPDATE_SUCCESS: "Cập nhật mã giảm giá thành công",
    UPDATE_FAILED: "Cập nhật mã giảm giá thất bại",
    HARD_DELETE_SUCCESS: "Xoá mã giảm giá thành công",
    DELETE_FAILED: "Xoá mã giảm giá thất bại",
    SOFT_DELETE_SUCCESS: "Đã xoá mềm mã giảm giá",
    REGISTER_SUCCESS: "Khôi phục mã giảm giá thành công",
    DETAIL_SUCCESS: "Chi tiết mã giảm giá",
  },
  CART: {
    CREATE_FAILED: "Tạo giỏ hàng thất bại",
    ALREADY_EXISTS: "Giỏ hàng đã tồn tại",
    ADD_ITEM_SUCCESS: "Đã thêm sản phẩm vào giỏ hàng.",
    ADD_ITEM_FAILED: "Thêm sản phẩm thất bại",
    PRODUCT_NOT_FOUND: "Sản phẩm không tồn tại.",
    VARIANT_NOT_FOUND: "Biến thể không tồn tại.",
    UPDATE_ITEM_SUCCESS: "Đã cập nhật số lượng sản phẩm.",
    UPDATE_FAILED: "Cập nhật thất bại",
    DELETE_ITEM_SUCCESS: "Đã xóa sản phẩm.",
    DELETE_FAILED: "Xóa sản phẩm thất bại",
    NOT_FOUND: "Không tìm thấy giỏ hàng.",
    ITEM_NOT_FOUND: "Không tìm thấy sản phẩm trong giỏ.",
    GET_SUCCESS: "Lấy giỏ hàng thành công",
    USER_ID_REQUIRED: "user_id là bắt buộc",
    CART_ID_PRODUCT_QUANTITY_REQUIRED:
      "cart_id, product_id và quantity là bắt buộc",
    QUANTITY_MINIMUM: "Số lượng phải lớn hơn hoặc bằng 1",
  },
};

export default messages;
